<a href="https://colab.research.google.com/github/Mr-Zainulabadin/python-lab-1/blob/main/W09_LAB_Programming_for_AI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Programming for Artificial Intelligence Lab 04

In [1]:
import pandas as pd

# What is DataFrame?

In [2]:
data={"name":["Bill","Tom","Tim","John","Alex","Vanessa","Kate"],
      "score":[90,80,85,75,95,60,65],
      "sport":["Wrestling","Football","Skiing","Swimming","Tennis",
               "Karete","Surfing"],
      "gender":["M","M","M","M","F","F","F"]}

In [3]:
df=pd.DataFrame(data)

In [4]:
df.head()

   name  score      sport gender
0  Bill     90  Wrestling      M
1   Tom     80   Football      M
2   Tim     85     Skiing      M
3  John     75   Swimming      M
4  Alex     95     Tennis      F

In [5]:
print(df.shape)
print(df.shape[0])
print(df.shape[1])

(7, 4)
7
4

In [6]:
df.tail()

      name  score     sport gender
2      Tim     85    Skiing      M
3     John     75  Swimming      M
4     Alex     95    Tennis      F
5  Vanessa     60    Karete      F
6     Kate     65   Surfing      F

In [7]:
df=pd.DataFrame(data,columns=["name", "sport", "gender", "score", "age"])
df

      name      sport gender  score  age
0     Bill  Wrestling      M     90  NaN
1      Tom   Football      M     80  NaN
2      Tim     Skiing      M     85  NaN
3     John   Swimming      M     75  NaN
4     Alex     Tennis      F     95  NaN
5  Vanessa     Karete      F     60  NaN
6     Kate    Surfing      F     65  NaN

In [8]:
df=pd.DataFrame(data,columns=["name", "sport", "gender", "score", "age"],
                index=["one","two","three","four","five","six","seven"])
df

          name      sport gender  score  age
one       Bill  Wrestling      M     90  NaN
two        Tom   Football      M     80  NaN
three      Tim     Skiing      M     85  NaN
four      John   Swimming      M     75  NaN
five      Alex     Tennis      F     95  NaN
six    Vanessa     Karete      F     60  NaN
seven     Kate    Surfing      F     65  NaN

In [9]:
df["sport"]

one      Wrestling
two       Football
three       Skiing
four      Swimming
five        Tennis
six         Karete
seven      Surfing
Name: sport, dtype: object

In [10]:
df.loc[["one"]]

     name      sport gender  score  age
one  Bill  Wrestling      M     90  NaN

In [11]:
df.loc[["one","two"]]

     name      sport gender  score  age
one  Bill  Wrestling      M     90  NaN
two   Tom   Football      M     80  NaN

In [12]:
df=pd.DataFrame(data,columns=["name", "sport", "gender", "score", "age"],
                index=["one","two","three","four","five","six","seven"])
values=[18,19,20,18,17,17,18]
df["age"]=values
df

          name      sport gender  score  age
one       Bill  Wrestling      M     90   18
two        Tom   Football      M     80   19
three      Tim     Skiing      M     85   20
four      John   Swimming      M     75   18
five      Alex     Tennis      F     95   17
six    Vanessa     Karete      F     60   17
seven     Kate    Surfing      F     65   18

In [13]:
df["pass"]=df.score>=70
df

          name      sport gender  score  age   pass
one       Bill  Wrestling      M     90   18   True
two        Tom   Football      M     80   19   True
three      Tim     Skiing      M     85   20   True
four      John   Swimming      M     75   18   True
five      Alex     Tennis      F     95   17   True
six    Vanessa     Karete      F     60   17  False
seven     Kate    Surfing      F     65   18  False

# Series Data Structure

In [14]:
obj=pd.Series([1,"John",3.5,"Hey"])
obj

0       1
1    John
2     3.5
3     Hey
dtype: object

In [15]:
obj.values

array([1, 'John', 3.5, 'Hey'], dtype=object)

In [16]:
obj2=pd.Series([1,"John",3.5,"Hey"],index=["a","b","c","d"])
obj2

a       1
b    John
c     3.5
d     Hey
dtype: object

In [17]:
obj2["b"]

'John'

# Working with Series Data Structure

In [18]:
!wget https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv

--2026-04-06 03:07:25--  https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1355781 (1.3M) [text/plain]
Saving to: ‘vgsalesGlobale.csv’

vgsalesGlobale.csv  100%[===================>]   1.29M  --.-KB/s    in 0.05s

2026-04-06 03:07:25 (24.6 MB/s) - ‘vgsalesGlobale.csv’ saved [1355781/1355781]

In [19]:
games=pd.read_csv("/content/vgsalesGlobale.csv", sep=',')

In [20]:
games

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...,...
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.00,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.00,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01

In [21]:
games.dtypes

Rank              int64
Name             object
Platform         object
Year            float64
Genre            object
Publisher        object
NA_Sales        float64
EU_Sales        float64
JP_Sales        float64
Other_Sales     float64
Global_Sales    float64
dtype: object

In [22]:
games.Genre.describe()

count      16598
unique        12
top       Action
freq        3316
Name: Genre, dtype: object

In [23]:
games.Genre.value_counts()

Genre
Action          3316
Sports          2346
Misc            1739
Role-Playing    1488
Shooter         1310
Adventure       1286
Racing          1249
Platform         886
Simulation       867
Fighting         848
Strategy         681
Puzzle           582
Name: count, dtype: int64

In [24]:
games.Genre.value_counts()

Genre
Action          3316
Sports          2346
Misc            1739
Role-Playing    1488
Shooter         1310
Adventure       1286
Racing          1249
Platform         886
Simulation       867
Fighting         848
Strategy         681
Puzzle           582
Name: count, dtype: int64

In [25]:
games.Genre.unique()

array(['Sports', 'Platform', 'Racing', 'Role-Playing', 'Puzzle', 'Misc',
       'Shooter', 'Simulation', 'Action', 'Fighting', 'Adventure',
       'Strategy'], dtype=object)

In [26]:
pd.crosstab(games.Genre, games.Year)

Year,1980.0,1981.0,1982.0,1983.0,1984.0,1985.0,1986.0,1987.0,1988.0,1989.0,...,2009.0,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0,2020.0
Genre,,,,,,,,,,,,,,,,,,,,,
Action,1,25,18,7,1,2,6,2,2,2,...,272,226,239,266,148,186,255,119,1,0
Adventure,0,0,0,1,0,0,0,1,0,0,...,141,154,108,58,60,75,54,34,0,0
Fighting,1,0,0,0,0,1,0,2,0,0,...,53,40,50,29,20,23,21,14,0,0
Misc,4,0,1,1,1,0,0,0,0,1,...,207,201,184,38,42,41,39,18,0,0
Platform,0,3,5,5,1,4,6,2,4,3,...,29,31,37,12,37,10,14,10,0,0
Puzzle,0,2,3,1,3,4,0,0,1,5,...,79,45,43,11,3,8,6,0,0,0
Racing,0,1,2,0,3,0,1,0,1,0,...,84,57,65,30,16,27,19,20,0,0
Role-Playing,0,0,0,0,0,0,1,3,3,2,...,103,103,95,78,71,91,78,40,2,0
Shooter,2,10,5,1,3,1,4,2,1,1,...,91,81,94,48,59,47,34,32,0,0
Simulation,0,1,0,0,0,1,0,0,1,0,...,123,82,56,18,18,11,15,9,0,1
Sports,1,4,2,1,2,1,3,4,2,3,...,184,186,122,54,53,55,62,38,0,0
Strategy,0,0,0,0,0,0,0,0,0,0,...,65,53,46,15,19,8,17,10,0,0

In [27]:
games.Global_Sales.mean()

np.float64(0.5374406555006628)

# Summarizing & Computing Descriptive Statistics

In [28]:
import pandas as pd
import numpy as np

In [29]:
df=pd.DataFrame([[2.4,np.nan],[6.3,-5.4],[np.nan,np.nan],[0.75,-1.3]],
                index=["a","b","c","d"],
                columns=["one","two"])
df

    one  two
a  2.40  NaN
b  6.30 -5.4
c   NaN  NaN
d  0.75 -1.3

In [30]:
df.sum()

one    9.45
two   -6.70
dtype: float64

In [31]:
df.sum(axis=1)

a    2.40
b    0.90
c    0.00
d   -0.55
dtype: float64

In [32]:
df.idxmax()

one    b
two    d
dtype: object

# Indexing & Selection & Filtering in Pandas

In [33]:
obj=pd.Series(np.arange(5),
              index=["a","b","c","d","e"])

obj

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [34]:
obj["c"]

np.int64(2)

In [35]:
print(obj[["a","c"]])
print(obj[[0,2]])

a    0
c    2
dtype: int64
a    0
c    2
dtype: int64

/tmp/ipykernel_2151/1046677006.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(obj[[0,2]])

# DataFrame Indexing

In [36]:
data=pd.DataFrame(
    np.arange(16).reshape(4,4),
    index=["London","Paris",
           "Berlin","Istanbul"],
    columns=["one","two","three","four"])
data

          one  two  three  four
London      0    1      2     3
Paris       4    5      6     7
Berlin      8    9     10    11
Istanbul   12   13     14    15

In [37]:
data[["one","two"]]

          one  two
London      0    1
Paris       4    5
Berlin      8    9
Istanbul   12   13

In [38]:
data[:3]

        one  two  three  four
London    0    1      2     3
Paris     4    5      6     7
Berlin    8    9     10    11

In [39]:
data[data["four"]>5]

          one  two  three  four
Paris       4    5      6     7
Berlin      8    9     10    11
Istanbul   12   13     14    15

# Selecting with iloc and loc

In [40]:
data.iloc[1]

one      4
two      5
three    6
four     7
Name: Paris, dtype: int64

In [41]:
data.iloc[1,[1,2,3]]

two      5
three    6
four     7
Name: Paris, dtype: int64

In [42]:
data.iloc[[1,3],[1,2,3]]

          two  three  four
Paris       5      6     7
Istanbul   13     14    15

In [43]:
data.loc["Paris",["one","two"]]

one    4
two    5
Name: Paris, dtype: int64

# Lab Task 01

Import the necessary libraries

In [44]:
# YOUR CODE HERE
import pandas as pd

1. Download the movie dataset from this website (Download it manually) https://www.kaggle.com/datasets/iamsouravbanerjee/house-rent-prediction-dataset?select=House_Rent_Dataset.csv to your computer and upload it. Use that file and assign it to a dataframe called house_details

In [46]:
# YOUR CODE HERE
house_details = pd.read_csv("/content/House_Rent_Dataset.csv")

2. Display the first 15 rows

In [48]:
# YOUR CODE HERE
house_details.head(15)

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
0,2022-05-18,2,10000,1100,Ground out of 2,Super Area,Bandel,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner
1,2022-05-13,2,20000,800,1 out of 3,Super Area,"Phool Bagan, Kankurgachi",Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
2,2022-05-16,2,17000,1000,1 out of 3,Super Area,Salt Lake City Sector 2,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
3,2022-07-04,2,10000,800,1 out of 2,Super Area,Dumdum Park,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner
4,2022-05-09,2,7500,850,1 out of 2,Carpet Area,South Dum Dum,Kolkata,Unfurnished,Bachelors,1,Contact Owner
5,2022-04-29,2,7000,600,Ground out of 1,Super Area,Thakurpukur,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner
6,2022-06-21,2,10000,700,Ground out of 4,Super Area,Malancha,Kolkata,Unfurnished,Bachelors,2,Contact Agent
7,2022-06-21,1,5000,250,1 out of 2,Super Area,Malancha,Kolkata,Unfurnished,Bachelors,1,Contact Agent
8,2022-06-07,2,26000,800,1 out of 2,Carpet Area,"Palm Avenue Kolkata, Ballygunge",Kolkata,Unfurnished,Bachelors,2,Contact Agent
9,2022-06-20,2,10000,1000,1 out of 3,Carpet Area,Natunhat,Kolkata,Semi-Furnished,Bachelors/Family,2,Contact Owner
10,2022-05-23,3,25000,1200,1 out of 4,Carpet Area,"Action Area 1, Rajarhat Newtown",Kolkata,Semi-Furnished,Bachelors/Family,2,Contact Agent
11,2022-06-07,1,5000,400,1 out of 1,Carpet Area,Keshtopur,Kolkata,Unfurnished,Bachelors/Family,1,Contact Agent
12,2022-05-14,1,6500,250,1 out of 4,Carpet Area,"Tarulia, Keshtopur",Kolkata,Furnished,Bachelors,1,Contact Owner
13,2022-05-09,1,5500,375,1 out of 2,Carpet Area,Dum Dum Metro,Kolkata,Unfurnished,Bachelors/Family,1,Contact Agent
14,2022-05-05,3,8500,900,Ground out of 2,Carpet Area,Paschim Barisha,Kolkata,Unfurnished,Bachelors,2,Contact Owner

3. Display the following columns with all rows

Posted On, Rent, city and Furnishing Status

In [49]:
# YOUR CODE HERE
house_details[["Posted On", "Rent", "City", "Furnishing Status"]]

       Posted On   Rent       City Furnishing Status
0     2022-05-18  10000    Kolkata       Unfurnished
1     2022-05-13  20000    Kolkata    Semi-Furnished
2     2022-05-16  17000    Kolkata    Semi-Furnished
3     2022-07-04  10000    Kolkata       Unfurnished
4     2022-05-09   7500    Kolkata       Unfurnished
...          ...    ...        ...               ...
4741  2022-05-18  15000  Hyderabad    Semi-Furnished
4742  2022-05-15  29000  Hyderabad    Semi-Furnished
4743  2022-07-10  35000  Hyderabad    Semi-Furnished
4744  2022-07-06  45000  Hyderabad    Semi-Furnished
4745  2022-05-04  15000  Hyderabad       Unfurnished

[4746 rows x 4 columns]

4. Find the total number of rows in your dataset?

In [50]:
# YOUR CODE HERE
house_details.shape[0]

4746

5. Find the total number of columns in your dataset?

In [51]:
# YOUR CODE HERE
house_details.shape[1]

12

6. Print the name of all the columns present in your dataset

In [52]:
# YOUR CODE HERE
house_details.columns

Index(['Posted On', 'BHK', 'Rent', 'Size', 'Floor', 'Area Type',
       'Area Locality', 'City', 'Furnishing Status', 'Tenant Preferred',
       'Bathroom', 'Point of Contact'],
      dtype='object')

Display the detail of houses that are Furnished

In [53]:
# YOUR CODE HERE
house_details[house_details["Furnishing Status"] == "Furnished"]

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
12,2022-05-14,1,6500,250,1 out of 4,Carpet Area,"Tarulia, Keshtopur",Kolkata,Furnished,Bachelors,1,Contact Owner
15,2022-06-01,3,40000,1286,1 out of 1,Carpet Area,New Town Action Area 1,Kolkata,Furnished,Bachelors/Family,2,Contact Owner
41,2022-05-12,3,12000,1500,Ground out of 2,Carpet Area,Bhadrakali,Kolkata,Furnished,Bachelors,2,Contact Owner
50,2022-06-22,1,7500,150,1 out of 1,Super Area,Salt Lake City,Kolkata,Furnished,Bachelors/Family,1,Contact Owner
82,2022-05-23,2,15000,480,Ground out of 3,Carpet Area,shukhobrishti,Kolkata,Furnished,Bachelors/Family,2,Contact Owner
...,...,...,...,...,...,...,...,...,...,...,...,...
4725,2022-05-14,1,9000,650,1 out of 3,Super Area,"Basheer Bagh, NH 7",Hyderabad,Furnished,Bachelors/Family,1,Contact Agent
4726,2022-05-14,2,16000,1100,2 out of 5,Super Area,"Basheer Bagh, NH 7",Hyderabad,Furnished,Family,2,Contact Agent
4727,2022-06-28,3,30000,214,2 out of 2,Super Area,Jubilee Hills,Hyderabad,Furnished,Bachelors,4,Contact Owner
4733,2022-06-28,1,5000,500,Ground out of 1,Carpet Area,BN Reddy Nagar,Hyderabad,Furnished,Bachelors/Family,1,Contact Owner
4735,2022-06-08,3,35000,1250,4 out of 5,Super Area,Raj Bhawan Road,Hyderabad,Furnished,Bachelors,2,Contact Owner

Now, display those houses that are furnished and have rent < 15K

In [54]:
house_details[(house_details["Furnishing Status"] == "Furnished") & (house_details["Rent"] < 15000)]

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
12,2022-05-14,1,6500,250,1 out of 4,Carpet Area,"Tarulia, Keshtopur",Kolkata,Furnished,Bachelors,1,Contact Owner
41,2022-05-12,3,12000,1500,Ground out of 2,Carpet Area,Bhadrakali,Kolkata,Furnished,Bachelors,2,Contact Owner
50,2022-06-22,1,7500,150,1 out of 1,Super Area,Salt Lake City,Kolkata,Furnished,Bachelors/Family,1,Contact Owner
84,2022-06-22,2,6700,800,1 out of 2,Super Area,"Baishnavghata patuli , house number s-300 Kolk...",Kolkata,Furnished,Bachelors/Family,1,Contact Owner
92,2022-05-15,1,9000,600,2 out of 4,Super Area,Behala,Kolkata,Furnished,Bachelors/Family,1,Contact Owner
...,...,...,...,...,...,...,...,...,...,...,...,...
4668,2022-04-30,2,12500,1100,2 out of 5,Super Area,"Vanasthalipuram, NH 9",Hyderabad,Furnished,Bachelors/Family,2,Contact Owner
4673,2022-07-02,2,8000,800,1 out of 6,Super Area,"Modi Paradise, Hayathnagar, Hyderabad",Hyderabad,Furnished,Bachelors/Family,2,Contact Owner
4703,2022-07-06,2,12000,950,4 out of 4,Super Area,"Anandbagh, Secunderabad, Moula Ali Road",Hyderabad,Furnished,Bachelors/Family,2,Contact Owner
4725,2022-05-14,1,9000,650,1 out of 3,Super Area,"Basheer Bagh, NH 7",Hyderabad,Furnished,Bachelors/Family,1,Contact Agent
4733,2022-06-28,1,5000,500,Ground out of 1,Carpet Area,BN Reddy Nagar,Hyderabad,Furnished,Bachelors/Family,1,Contact Owner

# Lab Task 02

Import the dataset from this address https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user without downloading it manually

In [56]:
import pandas as pd

In [55]:
# YOUR CODE HERE
!wget https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user

--2026-04-06 03:23:30--  https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 22667 (22K) [text/plain]
Saving to: ‘u.user’

u.user              100%[===================>]  22.14K  --.-KB/s    in 0.002s

2026-04-06 03:23:30 (13.8 MB/s) - ‘u.user’ saved [22667/22667]

Assign it to a variable called users and use the 'user_id' as index. choose the seperater/delimiter carefully.

In [57]:
# YOUR CODE HERE
users = pd.read_csv("/content/u.user", sep="|", index_col="user_id")

Display 1/3rd rows

In [58]:
# YOUR CODE HERE
users.head(3)

         age gender  occupation zip_code
user_id
1         24      M  technician    85711
2         53      F       other    94043
3         23      M      writer    32067

In [59]:
one_third = len(users) // 3

In [60]:
users.iloc[:one_third]

         age gender  occupation zip_code
user_id
1         24      M  technician    85711
2         53      F       other    94043
3         23      M      writer    32067
4         24      M  technician    43537
5         33      F       other    15213
...      ...    ...         ...      ...
310       37      M    educator    91711
311       32      M  technician    73071
312       48      M       other    02110
313       41      M   marketing    60035
314       20      F     student    08043

[314 rows x 4 columns]

Display the entire occupation column

In [61]:
# YOUR CODE HERE
users["occupation"]

user_id
1         technician
2              other
3             writer
4         technician
5              other
           ...
939          student
940    administrator
941          student
942        librarian
943          student
Name: occupation, Length: 943, dtype: object

How many different occupations are in this dataset?

In [62]:
# YOUR CODE HERE
users["occupation"].nunique()

21

What is the most occuring occupation for each gender seperatly?

In [63]:
# YOUR CODE HERE
users.groupby(["gender", "occupation"]).size().sort_values(ascending=False)

gender  occupation
M       student          136
        educator          69
        other             69
        engineer          65
F       student           60
M       programmer        60
        administrator     43
F       other             36
        administrator     36
M       executive         29
F       librarian         29
M       scientist         28
        technician        26
        writer            26
F       educator          26
M       librarian         22
F       writer            19
M       marketing         16
        entertainment     16
        artist            15
        retired           13
F       artist            13
        healthcare        11
        marketing         10
M       lawyer            10
        salesman           9
        doctor             7
F       homemaker          6
        programmer         6
M       none               5
        healthcare         5
F       none               4
        executive          3
        scientist          3
        salesman           3
        engineer           2
        entertainment      2
        lawyer             2
        retired            1
        technician         1
M       homemaker          1
dtype: int64

What is the mean age of users?

In [64]:
# YOUR CODE HERE
users["age"].mean()

np.float64(34.05196182396607)

Display the users who have age more than 40

In [65]:
# YOUR CODE HERE
users[users["age"] > 40]

         age gender     occupation zip_code
user_id
2         53      F          other    94043
6         42      M      executive    98101
7         57      M  administrator    91344
10        53      M         lawyer    90703
13        47      M       educator    29206
...      ...    ...            ...      ...
932       58      M       educator    06437
934       61      M       engineer    22902
935       42      M         doctor    66221
937       48      M       educator    98072
942       48      F      librarian    78209

[272 rows x 4 columns]

Find max and min value from each numeric column

In [66]:
# YOUR CODE HERE
users.select_dtypes(include="number").agg(["min", "max"])

     age
min    7
max   73

Find smallest and largest string from occupation column

In [71]:
# Smallest (alphabetically first)
smallest = users['occupation'].min()

# Largest (alphabetically last)
largest = users['occupation'].max()
smallest, largest

('administrator', 'writer')

Happy Coding :)